services:
  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot-network
    restart: unless-stopped

  # InfluxDB Database
  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - iot-network
    restart: unless-stopped

  # Event Processor
  processor:
    build: 
      context: ./processor
      dockerfile: Dockerfile
    container_name: iot-processor
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_ADDRESS=http://influxdb
      - INFLUX_PORT=8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ./processor:/app
    networks:
      - iot-network
    restart: unless-stopped

  # Plant Simulator
  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: iot-simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - TIME_MULTIPLIER=${TIME_MULTIPLIER:-10.0}
      - PIECE_COUNT=${PIECE_COUNT:-5}
    volumes:
      - ./simulator:/app
    networks:
      - iot-network
    restart: "no"  # Run once and stop

  # Dashboard (FastAPI)
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: iot-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    environment:
      - INFLUX_ADDRESS=http://influxdb
      - INFLUX_PORT=8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ./dashboard:/app
    networks:
      - iot-network
    restart: unless-stopped

# Networks
networks:
  iot-network:
    driver: bridge

# Volumes
volumes:
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local